/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Diagnosis = IDL.Record({
  'treatment' : IDL.Text,
  'careRecommendations' : IDL.Text,
  'issue' : IDL.Text,
});
export const PlantInfo = IDL.Record({
  'name' : IDL.Text,
  'type' : IDL.Text,
  'environment' : IDL.Text,
  'symptoms' : IDL.Vec(IDL.Text),
  'wateringHabits' : IDL.Text,
});

export const idlService = IDL.Service({
  'getAllDiagnoses' : IDL.Func([], [IDL.Vec(Diagnosis)], ['query']),
  'getDiagnosis' : IDL.Func([], [Diagnosis], ['query']),
  'searchDiagnosesByIssue' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Diagnosis)],
      ['query'],
    ),
  'submitPlantInfo' : IDL.Func([PlantInfo], [Diagnosis], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Diagnosis = IDL.Record({
    'treatment' : IDL.Text,
    'careRecommendations' : IDL.Text,
    'issue' : IDL.Text,
  });
  const PlantInfo = IDL.Record({
    'name' : IDL.Text,
    'type' : IDL.Text,
    'environment' : IDL.Text,
    'symptoms' : IDL.Vec(IDL.Text),
    'wateringHabits' : IDL.Text,
  });
  
  return IDL.Service({
    'getAllDiagnoses' : IDL.Func([], [IDL.Vec(Diagnosis)], ['query']),
    'getDiagnosis' : IDL.Func([], [Diagnosis], ['query']),
    'searchDiagnosesByIssue' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Diagnosis)],
        ['query'],
      ),
    'submitPlantInfo' : IDL.Func([PlantInfo], [Diagnosis], []),
  });
};

export const init = ({ IDL }) => { return []; };